inputs:
- branch: master
  path: ".tekton/ci"
  type: git
  service: ${tekton-pipeline-repo}
- branch: master
  path: git
  type: git
  service: ${tekton-task-repo}
- branch: master
  path: container-registry
  type: git
  service: ${tekton-task-repo}
- branch: master
  path: kubernetes-service
  type: git
  service: ${tekton-task-repo}
properties:
- name: apikey
  type: SECURE
  value: ${API_KEY}
- name: appName
  type: TEXT
  value: ${APP_NAME}
- name: clusterName
  type: TEXT
  value: mycluster
- name: branch
  type: TEXT
  value: ${GIT_BRANCH}
- name: imageName
  type: TEXT
  value: ${IMAGE_NAME}
- name: repository
  type: TEXT
  value: ${source-repo-url}
- name: registryDomain
  type: TEXT
  value: us.cr.io # ${REGISTRY_REGION_ID}
- name: registryNamespace
  type: TEXT
  value: ${REGISTRY_NAMESPACE}
- name: policyName
  type: TEXT
  value: ${POLICY_NAME}
- name: umbrellaRepoName
  type: TEXT
  value: ${UMBRELLA_REPO_NAME}
triggers:
- eventListener: event-listener-manual-run
  name: Manual Trigger
  type: manual
- branch: master
  eventListener: event-listener-git-commit
  events:
    push: true
  name: Git Trigger
  type: git
  service: ${source-repo}
