apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: unit-test-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: appName
        description: Logical application name for DevOps Insights
      - name: continuous-delivery-context-secret
        description: name of the configmap containing the continuous delivery pipeline context secrets
        default: cd-secret
  steps:
    - name: run-tests
      image: ibmcom/pipeline-base-image
      workingDir: /artifacts
      env:
        - name: APP_NAME
          value: $(inputs.params.appName)         
        - name: IBM_CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.continuous-delivery-context-secret)
              key: API_KEY
              optional: true
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail
          ##########################################################################
          # Setting HOME explicitly to have ibmcloud plugins available
          # doing the export rather than env definition is a workaround
          # until https://github.com/tektoncd/pipeline/issues/1836 is fixed
          # and until 0.11 - https://ibm.ent.box.com/notes/599948660131?s=rqk76zkkdsz1cenvpw0ad8enxul6j0nv
          export HOME=/root && source ~/.nvm/nvm.sh
          ##########################################################################
          source ./build.properties
          export TOOLCHAIN_ID=${TOOLCHAIN_ID} # for doi plugin
          if [ -f ./tests/run-tests.sh ]; then
            source ./tests/run-tests.sh
          else
            echo "Test runner script not found: ./tests/run-tests.sh"
          fi
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json